name: Deploy with Pages Artifact

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install pygbag
        run: pip install pygbag

      - name: Build with pygbag
        run: pygbag --build .



      # ────────────────────────────────────────────────
      # Copy & dereference symlinks into a fresh folder
      - name: Prepare deploy folder
        run: |
          mkdir deploy
          rsync -aL . deploy/
          rm -rf deploy/.github  # don't publish GitHub configs
      # ────────────────────────────────────────────────

      - name: Upload GitHub Pages artifact
        uses: actions/upload-artifact@v4.6.2
        with:
          path: ./build/web
          name: github-pages

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
